### PR TITLE
Bug/accessibility1

### PR DESCRIPTION
**Pull request by jacobvenable**
# Accessibility Updates
Included in this merge are accessibility updates to the templates that include color changes, keyboard navigation modifications, icon link content, and skip-to navigation links.

## Colors
- **Campus Gold:** Changing from #B1810B to #c28e0e
- **Headline Gold (new):** Using #98700D as the gold color of the headlines.
- **Slayter Sky Blue:** Changing from #7ca6c0 to #6e99b4
- **Bell Tower Brick:** Changing from #c76c14 to #b46012
- **Fountain Run Teal:** Changing from #2eaf9b to #29a592

With these color changes, various elements, namely those using the new Campus Gold, needed modified to work with the new colors. For example, the Gold Bar will now use black text on the new Campus Gold instead of white text. See the following SCSS partials to see updates to specific content:
- Gold Bar - [_goldBar.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-2016e7a28a82090c16834deb9e4d19c3)
- College Template Main Content - [_collegeContent.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-694f7332b099e3419109db10dfe78281)
- Dept/Office Template Main Content - [_deptOfficeContent.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-19ddba7813cd6578bb24ecfbc0a5fff7)
- Events Template Main Content -  [_eventsContent.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-c6803d972bcebeb116e1e354a75cabe7)
- Audience Template Main Content - [_audienceContent.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-03f66bfbf80f1c1ad5376b58ab344057).

### Dropdown Menu Links Focus Outlines
Dropdown menu links were not showing an outline on focus. This made it difficult for keyboard users to determine where their current focus on the page was. This was corrected by implementing a new SCSS partial, [_bootstrap-fixes](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-df41ee534561bd217d4a177d71ca605b).

### Main Navigation Sub-dropdown Menus
There was an issue with being able to open sub-dropdown navigation items in the main navigation. Before, the sub-dropdown menu would open on hover; however, this doesn't work when navigating a keyboard. If a keyboard-navigating user would click on the sub-dropdown link, it would close the dropdown that the sub-dropdown link was located in.

The solution was to have to convert the menus from always being "removed" from the page (display:none) until hover, to always being part of the page (display:block) but visibly hidden. When the sub-dropdown link is focused, it will display the corresponding sub-dropdown menu, normally. When the user moves forward from the sub-dropdown link, there will be a brief millisecond when the focus is removed from the sub-dropdown link. Since the sub-dropdown menu is still displayed, it will be able to focus on the first sub-dropdown menu link.

See [_goldBar.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-2016e7a28a82090c16834deb9e4d19c3) for changes to that partial.

_A drawback to this method is that only the currently focused sub-dropdown menu link will be visible at a time. We will be looking for a more elegant solution in the future._

## Icon Link Content
Initially links in the gold bar (search) and footer (social media) didn't have content that would indicate the link destination. This was modified via CSS by using :after to insert the content. See [_goldBar.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-2016e7a28a82090c16834deb9e4d19c3) and [_footer.scss](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-d40fd8947819827b8d25f5a8116d429e).

## Skip To Navigation Links
Although many screen readers are able to navigate a properly marked-up page with ease, it is safe to also provide a way to skip to the main content of the page. There is now the option to add the skip-to [html](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-40944156cac230d9c692f35f52ad4563) to the top of your pages and [styles](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-98eb93a6badd1e1af8e2f7f30698b481) to each of the template styles. You will have to ensure that you add the id of "main" to the container of your main content. [Example](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/compare/master-temp...bug/accessibility1?expand=1#diff-3ccf3ed953bcf785d0fd484e582304c0)

### CODE REVIEW

**Comment by jobokai** [comment]
> Headline Gold (new): Using #98700 as the gold color of the headlines. 
I think there's a typo there with the hex value. You may want to correct.

**Comment by jacobvenable** [comment]
@jobokai That has been updated to #98700D. Thanks for pointing that out

**Comment by jacobvenable** [comment]
We are going to make these changes live tomorrow morning which means that I will be merging this pull request at the end of today. If you need to continue referencing this pull request, you will be able to find it categorized under closed pull requests. Thanks!

**Comment by purduekenny** [comment]
@jacobvenable is there a reason why you added bootstrap_fixes for .dropdown-toggle instead of just removing the class from the HTML? It seems superfluous. Was it just so that people wouldn't have to go and edit their HTML if they updated their CSS? I'm asking because Ag just removed the class long ago and we haven't seen any ill effects.

**Comment by jacobvenable** [comment]
@purduekenny Good point. With these updates, we were aiming to provide changes with little to no end-user responsibility. With Cascade, HTML changes happen in bulk rather than section-by-section, so we can't force an update to just the gold-bar navigation or just the top-navigation without republishing a whole website. Since we don't manage end-user content, we didn't want to force site-wide publishes and risk having incomplete content make it to production.

So instead, we decided to just override Bootstrap's styles within the CSS which will go out to all sites using our CSS without end-users needing to do anything. However, you do make a good point that it is unnecessary. We can revisit this in a future update that will come with some other needed clean-up. Thanks for letting us know Ag's approach.

**Comment by jobokai** [comment]
@jacobvenable do you happen to know what the timeline for the rollout looks like? Not that it affects what I'm working on just curious ;)

**Comment by jacobvenable** [comment]
@jobokai I'm moving these updates into development right now. After some testing, I will make it live today!

**Pull request merged**
