### PR TITLE
Feat/add browser compatibility

### PR DESCRIPTION
**Pull request by jyoung295**
Moving #100 to this pull request to change branch name.

### CODE REVIEW

**Comment by jyoung295** [comment]
Safari is having a really weird visual bug with the YouTube video in the side content. Also in the side nav the gold underline is not working, see gif:

[Image from Gyazo](https://gyazo.com/8447bceafb7eed4ffe71591ce02b1cce)

**Comment by jyoung295** [comment]
Accordions on the example page are snapping closed instead of sliding closed like the ones in the footer.

**Comment by jyoung295** [comment]
Edge (left) and Chrome (middle) render the image differently than Firefox (right).

[Image from Gyazo](https://gyazo.com/8906111ad5cdd2aa465d2c277366d5cc)

It appears stretched on chromium browsers.

**Comment by jyoung295** [comment]
> Edge (left) and Chrome (middle) render the image differently than Firefox (right).
> 
> [Image from Gyazo](https://gyazo.com/8906111ad5cdd2aa465d2c277366d5cc)
> 
> The image is being stretched vertically on all browsers, but appears even more stretched on chromium browsers.

This has been fixed in afb7b30

**Comment by jyoung295** [comment]
> Safari is having a really weird visual bug with the YouTube video in the side content. Also in the side nav the gold underline is not working, see gif:
> 

Visual Bug with the video player is still there, but the missing underline has been fixed in d830d04

**Comment by jyoung295** [comment]
We should think about re-working the button styles too because Jacob built them with pseudo-elements because it makes it easy to create slimmer and wider buttons with differing amounts of space, but when we were originally discussing the buttons, I had suggested just using flex, but it seemed Jacob was set on the pseudo element version.

The way they're currently built, they work in IE but don't have the same spacing inside the button because pseudo elements can be tricky in IE.

**Comment by jyoung295** [comment]
[Here on Codepen](https://codepen.io/young295/pen/JgJGrO?editors=1100) you can see an example I wrote for the first two sets of buttons of what I think is a better way to write them.

**Comment by Yanhuazong** [comment]
> Safari is having a really weird visual bug with the YouTube video in the side content. Also in the side nav the gold underline is not working, see gif:
> 
> [Image from Gyazo](https://gyazo.com/8447bceafb7eed4ffe71591ce02b1cce)

Aug-09-2019 09-49-09
This seems to only happen on additional monitors. On the monitor of my laptop the visual bug doesn't show up.

**Comment by jyoung295** [comment]
Weird, well it must be a Safari bug so there's nothing we can do about it.

**Pull request merged**
