### PR TITLE
Hotfix 1.6.7

### PR DESCRIPTION
**Pull request by jacobvenable**
This update includes various fixes, enhancements, and updates to placeholder content.

## General

- Updated the version number within `package.json` for possible use in #35.
- Update viewport meta to allow scaling and provide an initial scale of 1
- Updated placeholder content on most pages.

## Gold Bar

- Add visibly-hidden text to the desktop and mobile search buttons. Also add `aria-hidden="true"` to the search icons to hide the text that was originally inserted via CSS.

## Header

- Implemented #68 by adding the `logo-noBorder` class modifier to the logo found in the header. Currently, this is only used on Purdue's home page, but it could possibly be implemented elsewhere.

## Footer

- Addresses #74 by adding a visibly-hidden, "Resources" `<h2>` before the four footer columns.
- Addresses #18 by placing visibly-hidden text within each of the social-media links instead of relying on the title attribute. This also adds `aria-hidden="true"` to each of the FontAwesome `<i>` elements to hide the text originally placed there via CSS.
- Adds `role="button"` to each of the `<a>` elements found within the column headers to indicate they act as a button at mobile rather than as a link. When the footer is refactored, we'll want to implement these as `<button>` elements.
- Updated the readme with development instructions.

## Audience Page

- Addresses #76 by increasing most headings found at the start of rows from `<h3>` to `<h2>`. Styles originally applied to `<h3>` were applied to both heading levels for backwards compatibility.
- Addresses #73 by setting images found within events on the events row as hidden.
- Add visibly-hidden `<h2>` to the Twitter row to indicate the section contains tweets from an account.
- Add example of an Instagram feed generated via Tint.

## Department Office Page
- Remove margins from the sub-headers found in the hero area.

### CODE REVIEW

**Comment by jacobvenable** [comment]
Ah, no I'll need to add that as well. I'll also create a Gist containing the CSS that would be applied to the Tint Feed itself.

**Comment by jacobvenable** [comment]
I added an example row that uses Tint; however, it doesn't look like I can create a Gist that sits under the organization rather than my personal account.

**Comment by jyoung295** [comment]
Everything looks good to me. Is that the last of the changes?

**Comment by jacobvenable** [comment]
Yep, I believe so! Any other issues will probably be included in a future release. Thanks for looking!

**Pull request merged**
