### PR TITLE
Finalize Button Styles (but really this time)

### PR DESCRIPTION
**Pull request by jacobvenable**
## Updates

To see a preview of all button types, you can reference the [button pattern page](https://dev.www.purdue.edu/pmmtest/templates/testing/button/templates/patterns/button.html) within our testing area.

### Limit Colors
After taking a second look at our original implementation of the button pattern, we decided that we wanted to limit the number of available brand colors that could be used with a button. This decision only applies to buttons used within the Purdue templates, and doesn't limit the use of other brand-colored buttons on non-templated (but in brand) sites.

### Button with Icon
An additional style of button was added, which includes an icon placed on the right side of the button.
example of button using an icon

### Simpler Class Implementations
In the original implementation, applying color and/or light modifiers were a bit confusing since their implementation depended on the button's base style. There are now single classes for applying separate button styles.

#### Base Class

- **button** : the base button class that is need on every button.

    - **at rest** : No outline, solid Campus Gold background, black text
    - **on hover/focus** : Campus Gold outline, transparent background, black text

#### Type Modifiers

- **button-hollow** : reverses the initial state of the button

    - **at rest** : Campus Gold outline, transparent background, black text
    - **on hover/focus** : No outline, solid Campus Gold background, black text

- **button-bar** : adds a darkened bar to the bottom of the default button

    - **at rest** : No outline, darkened Campus Gold bottom bar, solid Campus Gold background, black text
    - **on hover/focus** : darkened Campus Gold outline, darkened Campus Gold bottom bar, transparent background, black text

- **button-icon** : removes hover/focus styles from the default button (hover/focus styles are placed on the contained `.button__icon` element instead)

    - **at rest** : No outline, darkened Campus Gold bottom bar, solid Campus Gold background, black text
    - **on hover/focus** : No outline, darkened Campus Gold bottom bar, solid Campus Gold background, black text

- **button-opaque** : replaces default button styles with a dark, opaque button (used to be placed over photos)

    - **at rest** : black outline, 50% opaque black background, white text
    - **on hover/focus** : No outline, solid black background, white text

#### Color Modifiers

These classes modify the base button classes (above) to use a different pairing of colors

- **button-campusGold** : updates the button to use **campus gold** and **black** as the base colors for styles (default).
- **button-campusGold-inverse** : updates the button to use the inverse of `button-campusGold` class as the base colors for styles. Wherever campus gold is used, **black** will be used and vice versa.
- **button-black** : updates the button to use **black** and **white** as the base colors for styles.
- **button-gray70** : updates the button to use **70% gray** and **white** as the base colors for styles.
- **button-gray40** : updates the button to use **40% gray** and **white** as the base colors for styles.
- **button-gray15** : updates the button to use **15% gray** and **white** as the base colors for styles.

#### Light Modifier
- **button-light** : This class can be added to a button to ensure that it provides enough color contrast when the button is placed on a darker background. For example, placing this modifier on the default button will change the hover/focus text color to be white instead of black.

#### Wide Modifiers
- **button-wide** : This class can be added to a button to have it be span the full width of its parent at all screen sizes.
- **button-wide-lg** : This class can be added to a button to have it be span the full width of its parent at the large (lg) Bootstrap breakpoint size.
- **button-wide-md** : This class can be added to a button to have it be span the full width of its parent at the medium (md) Bootstrap breakpoint size.
- **button-wide-sm** : This class can be added to a button to have it be span the full width of its parent at the small (sm) Bootstrap breakpoint size.
- **button-wide-xs** : This class can be added to a button to have it be span the full width of its parent at the extra-small (xs) Bootstrap breakpoint size.

#### Element Classes
- **button__icon** : This class is placed on the button's icon element. This is to be used within a button that uses the `button-icon` class.

    - **at (parent button's) rest** : no outline, black background, white icon
    - **on (parent button's) hover/focus** : no outline, black background, 10% enlarged campus gold icon

## Conversation Points

- Should we just remove the `button-campusGold` class since it is automatically applied via the base `button` class?
- We should consider looking into a better templating tool for this repository. Currently, we're using [gulp-file-include](https://www.npmjs.com/package/gulp-file-include) for our HTML, but it is a bit limiting when you try to carry out more complex functions. A good example of trying to build a class to be placed on a button in the [button-container](https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/pull/39/files#diff-59601629a0c416e62a92d0c346595890) HTML module.
- While implementing classes on a button is easier with this update, it is also more specific. For example, the `button-light` class needs to affect solid buttons and hollow buttons differently. To achieve this, I had to use multi-class selectors to, i.e. `.button-hollow.button-light`. If we need to implement a different class to override these styles, it may have trouble being specific enough.

### CODE REVIEW

**Comment by jobokai** [comment]
Just being devil's advocate here: is the icon color and font size increase enough to signify user interaction? It feels like when using :focus from the keyboard it's not very obvious what you are actually focusing unlike the other buttons. 

Non devil's advocate: I like the direction and styling of them. It's very a very clean look :)

**Comment by jacobvenable** [comment]
Ya, I can definitely see that. I'll bring it up to our designer. Maybe we can re-implement the color changes on hover for the main area of the button as well.

**Comment by jobokai** [comment]
Doing some in browser editing, I think it would work to carry over the hover effect from the other buttons to the 'main' area of this new button type.

**Comment by jacobvenable** [comment]
@jobokai These latest commits also added an outline to the button using the icon and remove the icon resizing on hover, per our designer's request.

I believe that pending no other issues, these are ready to go.

**Pull request merged**
